name: app_acessibilidade
description: Aplicativo para avaliação de acessibilidade.

dependencies:
  cloud_firestore: ^0.8.2+1

  pdf: ^1.0.7

  flutter:
    sdk: flutter
  shared_preferences: ^0.4.1

  firebase_database:

  firebase_auth: ^0.5.20
  google_sign_in: ^3.2.1

cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - imagens/acessibilidadeONU.jpg
    - imagens/portaComRevestimentoEpuxadorHorizontal.jpg
    - imagens/macanetasEpuxadores.jpg
    - imagens/sanitarioFemininoAcessivel.png
    - imagens/sanitarioMasculinoAcessivel.png
    - imagens/sanitarioFamiliarAcessivel.png

