name: app_acessibilidade
description: Aplicativo para avaliação de acessibilidade.

dependencies:
  cloud_firestore: ^0.7.3

  flutter:
    sdk: flutter

  firebase_auth: 0.5.20

cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - imagens/acessibilidadeONU.jpg

